### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by ilyasky87** [skavngr/netbot#1]
python3 netbot_server.py
 ______             ______
|  ___ \       _   (____  \       _
| |   | | ____| |_  ____)  ) ___ | |_
| |   | |/ _  )  _)|  __  ( / _ \|  _)
| |   | ( (/ /| |__| |__)  ) |_| | |__
|_|   |_|\____)\___)______/ \___/ \___)1.0 from https://github.com/skavngr

Traceback (most recent call last):
  File "/netbot/netbot_server.py", line 67, in <module>
    Main()
  File "/netbot/netbot_server.py", line 53, in Main
    s.bind((host, port))
OSError: [Errno 99] Cannot assign requested address

Testing OS - Kali Nethunter. What wrong ?

**Comment by sh4nx0r** [comment]
@ilyasky87 Please try to run the code using the sudo privileges. `sudo python3 netbot_server.py`

**Comment by ilyasky87** [comment]
I've tried with sudo it doesn't work =(  help me please

**Comment by sh4nx0r** [comment]
@ilyasky87 ,  What is the IP address of your virtual machine? Make sure you are not on NAT mode, try with bridged mode and let me know the outcome.

**Comment by ilyasky87** [comment]
Here I am a noob! It was necessary to change the ip address to the local one in the netbot_server.py settings and also in netbot_client.py =) But I thought that everything was already set up. Now I will test

**Comment by sh4nx0r** [comment]
@ilyasky87, Apologies for the late response. Glad that you were able to set it up. Ping of Death attack is quite old and there are high chances that your attacks are filtered by the firewall. Did you try reproducing it on your lab environment first?

**Comment by ilyasky87** [comment]
Hey! I was very busy, today I will continue my research =)
