### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by silkyearth** [skavngr/netbot#2]
its just blank when i run python3 netbot_server.py ....
how do i get server online. 
it says ccc not online

**Comment by sh4nx0r** [comment]
@silkyearth , you should also run `netbot_client.py` on another terminal or machine. Most importantly, change the ip address in the `netbot_client.py` code to suit your CCC server address, else it will show CCC not online as you are facing now.

**Comment by silkyearth** [comment]
@sh4nx0r what do i set the ip address to?

**Comment by sh4nx0r** [comment]
@silkyearth It should be the ip address of the machine where the `netbot_server.py` (ccc) code is running.

**Comment by silkyearth** [comment]
@sh4nx0r I figured it out, simple fix. Just needed to leave port as is and change the ip address.
